### ISSUE TITLE
aktualizace dat v mapach

### ISSUE THREAD

**Issue by ivanahepjuk** [dron23/SensoricNet-mqtt-influxdb#1]
Zdar, nevim jestli to patri sem, ale vypada to ze se nejak divne aktualizuji data. Sensor mam zaply a pritom ukazuje par dni stare hodnoty. Vidim ho na mape. Kdyz ho flashnu jako nbiot-0002 tak do grafany chodi data v poradku, ale na mape se nezobrazi :) Kde je ten kod pro mapy? Dela na tom nekdo?

**Comment by dron23** [comment]
mapy rostou tady https://github.com/dron23/SensoricNet-maps (respektive je to fork od dejva, ale on moje lehke upravy jeste nemergnul... co @daveOVApage?). K tomu, aby se aktualizovaly data v mapách, tak musí data dorazit na api a navím musí být rozparsovaná data (=jednotlivé veličiny) správně zavedeny v databázi. Tento konkrétní problém byl zřejmě o tom, že si začal posílat nějaká data navíc (NBIoT statistiky?), která nejsou zavedena v db api. Ona pak failne transakce a nevloží se nic. Je to tak "by design", kdyžtak přehoď tohle issue do api.
